# Generated by Django 5.0.4 on 2024-04-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calibration',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('location', models.TextField(blank=True, null=True, unique=True)),
                ('calibration', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'calibration',
            },
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('device', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('location', models.TextField(blank=True, null=True)),
                ('port', models.TextField(blank=True, null=True)),
                ('calibration', models.FloatField(blank=True, null=True)),
                ('cal_pow', models.FloatField(blank=True, null=True)),
                ('changed', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'devices',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('location', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('location', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('code', models.TextField(blank=True, null=True)),
                ('time', models.DateTimeField(blank=True, null=True, unique=True)),
                ('fix_description', models.TextField(blank=True, null=True)),
                ('fix_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'issues',
            },
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('location', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('nickname', models.TextField(blank=True, null=True)),
                ('tzoffset', models.IntegerField(blank=True, null=True)),
                ('lastseen', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'locations',
            },
        ),
        migrations.CreateModel(
            name='Rawcurrent',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('location', models.TextField(blank=True, null=True)),
                ('current', models.FloatField(blank=True, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rawcurrent',
            },
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('endpoint', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('subscription', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subscriptions',
            },
        ),
    ]
