# Generated by Django 5.0.5 on 2024-05-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawcurrent',
            name='current',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='rawcurrent',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
