# Generated by Django 5.0.5 on 2024-05-09 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0002_alter_rawcurrent_current_alter_rawcurrent_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laundry.location'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laundry.location'),
        ),
    ]
