# Generated by Django 5.0.5 on 2024-10-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0002_usersite_user_site_index'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['location', 'time', 'status'], name='event_index'),
        ),
    ]
