# Generated by Django 5.0.5 on 2025-07-16 14:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0003_event_event_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersite',
            unique_together={('user', 'site')},
        ),
    ]
