# Generated by Django 5.0.5 on 2024-05-21 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0007_usersite'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='ooo',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
