# Generated by Django 5.0.5 on 2024-05-22 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0008_issue_ooo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='laundry.location'),
        ),
    ]
