# Generated by Django 5.0.5 on 2024-05-22 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0009_alter_device_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='laundry.site'),
        ),
    ]
