# Generated by Django 5.0.5 on 2024-05-22 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0010_device_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='laundry.site'),
        ),
    ]
