# Generated by Django 5.0.5 on 2024-05-22 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0011_alter_device_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='laundry.site'),
        ),
    ]
