# Generated by Django 5.0.5 on 2024-05-31 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0012_issue_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationtype',
            name='processor',
            field=models.TextField(default='generic'),
        ),
    ]
