# Generated by Django 5.0.5 on 2024-06-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0013_locationtype_processor'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationtype',
            name='type',
            field=models.TextField(default='dryer'),
        ),
        migrations.AlterField(
            model_name='locationtype',
            name='processor',
            field=models.TextField(choices=[('generic', 'Generic'), ('generic_dryer', 'Generic Dryer'), ('generic_washer', 'Generic Washer'), ('whirlpool_washer', 'Whirlpool Washer'), ('maytag_stack', 'Maytag Stack')], default='generic'),
        ),
    ]
