# Generated by Django 5.0.5 on 2024-06-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0014_locationtype_type_alter_locationtype_processor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationtype',
            name='type',
            field=models.TextField(choices=[('W', 'washer'), ('D', 'dryer'), ('S', 'stack')], default='dryer'),
        ),
    ]
