# Generated by Django 5.0.5 on 2024-06-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0015_alter_locationtype_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='display_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
