# Generated by Django 5.0.5 on 2024-06-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0016_location_display_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['site', 'section', 'display_order', 'nickname']},
        ),
        migrations.AddField(
            model_name='location',
            name='section',
            field=models.TextField(blank=True, null=True),
        ),
    ]
