# Generated by Django 5.0.5 on 2024-06-03 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0018_alter_location_nickname_alter_location_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('display_order', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='location',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='laundry.section'),
        ),
    ]
