# Generated by Django 5.0.5 on 2024-06-03 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0019_section_alter_location_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='laundry.site'),
        ),
    ]
