# Generated by Django 5.0.5 on 2024-06-03 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0021_alter_location_section_alter_location_site'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['site', 'section', 'display_order', 'name']},
        ),
        migrations.RenameField(
            model_name='location',
            old_name='nickname',
            new_name='name',
        ),
    ]
