# Generated by Django 5.0.5 on 2024-06-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0022_alter_location_options_rename_nickname_location_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='rawcurrent',
            index=models.Index(fields=['time'], name='time_idx'),
        ),
    ]
