# Generated by Django 5.0.4 on 2024-06-21 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0023_rawcurrent_time_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['site', 'display_order', 'name']},
        ),
        migrations.AddField(
            model_name='location',
            name='record_enable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.TextField(blank=True, choices=[('wash', 'washing'), ('dry', 'drying'), ('both', 'both'), ('none', 'idle'), ('offline', 'offline'), ('ooo', 'out of order')], null=True),
        ),
        migrations.AlterField(
            model_name='locationtype',
            name='processor',
            field=models.TextField(choices=[('generic', 'Generic'), ('generic_dryer', 'Generic Dryer'), ('generic_washer', 'Generic Washer'), ('speedqueen_washer', 'Speedqueen Washer'), ('whirlpool_washer', 'Whirlpool Washer'), ('maytag_stack', 'Maytag Stack')], default='generic'),
        ),
    ]
